### ISSUE TITLE
github actionsの依存関係を記載する

### ISSUE THREAD

**Issue by dandk105** [dandk105/aws_lambda_test#4]
現状だと、goのbuildと、test実行と同時にawsにデプロイする事になっているから
goのbuildとawsのデプロイをわけたい

想定
```
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - run: ./build_server.sh
  aws_deploy:
    needs: build_and_test
    ^^^^^^^^^^^^ ここが依存ジョブの設定
    runs-on: ubuntu-latest
    steps:
      - run: ./test_server.sh
```
